AdobeDocs/adp-devsite

hlx_statics/blocks/herosimple/herosimple.css

Fixed the alignment issue in the HeroSimple block.

fix : herosimple alignment issue

---

hlx_statics/scripts/lib-helix.js
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

Added the GitHub actions block
Test URL : https://feat-github-actions-block--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/authentication/UserAuthentication/implementation

feat : added the github actions block

---

hlx_statics/blocks/onthispage/onthispage.css
hlx_statics/blocks/onthispage/onthispage.js

Implemented the onthispage block
Test URL : https://onthispage-fix--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/authentication/UserAuthentication/

Feat : Implemented the onthispage block

---

hlx_statics/blocks/breadcrumbs/breadcrumbs.css
hlx_statics/blocks/breadcrumbs/breadcrumbs.js
hlx_statics/blocks/side-nav/side-nav.js
hlx_statics/scripts/lib-helix.js
hlx_statics/styles/styles.css

**Ticket:** https://jira.corp.adobe.com/browse/DEVSITE-1233
**Description:** build breadcrumbs from sidenav and topnav
**Potential conflict:** https://github.com/adobe/adobe-io-website/pull/256/files
**Test:** https://breadcrumbs--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/authentication/UserAuthentication/implementation
**Compare with:** https://developer.adobe.com/developer-console/docs/guides/authentication/UserAuthentication/implementation/

Build breadcrumbs from sidenav and topnav

---

hlx_statics/scripts/lib-adobeio.js

update on analytics

---

hlx_statics/blocks/accordion/accordion.js
hlx_statics/blocks/cards/cards.js
hlx_statics/blocks/columns/columns.css
hlx_statics/blocks/list/list.css
hlx_statics/blocks/list/list.js
hlx_statics/blocks/site-hero/site-hero.css
hlx_statics/blocks/site-hero/site-hero.js
hlx_statics/blocks/tab/tab.css
hlx_statics/blocks/tab/tab.js
hlx_statics/blocks/teaser/teaser.css
hlx_statics/blocks/teaser/teaser.js
hlx_statics/blocks/text/text.css
hlx_statics/blocks/text/text.js
hlx_statics/blocks/video-carousel/video-carousel.css
hlx_statics/blocks/video-carousel/video-carousel.js
hlx_statics/scripts/lib-adobeio.js

Removing the use of section metadata for different variants.  Replace it with classnames.

Update on the components with different variants

---

hlx_statics/blocks/iframe/iframe.js
hlx_statics/blocks/info-card/info-card.js
hlx_statics/blocks/mini-resource-card/mini-resource-card.js
hlx_statics/blocks/resource-card/resource-card.js

Need to fix the previous PR where it's the applySectionTitle is removed.  I need to remove this from all the components.

Missing sectiontitle

---

hlx_statics/blocks/profile-card/profile-card.css

Change the margin to auto so that it'll be center on page.

update margin to be auto

---

hlx_statics/scripts/lib-adobeio.js

Update the hlx page to use aem page path as well.

update helix path

---

hlx_statics/blocks/announcement/announcement.css
hlx_statics/blocks/announcement/announcement.js

Merge the two components with teaser to announcement. 
https://devsite-1428-merge-announcement--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/test-announcement

Devsite 1428 merge announcement

---

hlx_statics/blocks/cards/cards.js
hlx_statics/blocks/edition/edition.js
hlx_statics/blocks/hero/hero.css
hlx_statics/blocks/hero/hero.js
hlx_statics/blocks/image-text/image-text.js
hlx_statics/blocks/link-block/link-block.css
hlx_statics/blocks/link-block/link-block.js
hlx_statics/blocks/list/list.css
hlx_statics/blocks/list/list.js
hlx_statics/blocks/profile-card/profile-card.css
hlx_statics/blocks/profile-card/profile-card.js
hlx_statics/blocks/tab/tab.js
hlx_statics/blocks/text/text.css
hlx_statics/blocks/text/text.js
hlx_statics/blocks/title/title.js
hlx_statics/scripts/lib-helix.js

Fix the rest of the components with the font color and change it based on the background color. 
Fixed the hero component as well. 
https://devsite-1417-font-color--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/

Removing font-color

---

hlx_statics/blocks/columns/columns.css
hlx_statics/blocks/columns/columns.js
hlx_statics/blocks/site-hero/site-hero.js

The center column was not properly render.
Also need to remove the font family for site-hero
https://bugfix-column--adp-devsite--adobedocs.aem.page/fund-for-design/index-onerepo

Fixing the center column and site-hero fonts

---

hlx_statics/blocks/header/header.js

Fix the navbar to be correctly rendered.

updating the navbar not loading

---

hlx_statics/blocks/info-card/info-card.css
hlx_statics/blocks/info-card/info-card.js
hlx_statics/blocks/mini-resource-card/mini-resource-card.css
hlx_statics/blocks/mini-resource-card/mini-resource-card.js

adding primary buttons for info cards and mini resource card.
https://louisa-devsite-1464-primary-button--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/test-mini-resource-card
https://louisa-devsite-1464-primary-button--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/test-info-card

update primary buttons for info cards and mini resource card

---

hlx_statics/blocks/tab/tab.css
hlx_statics/blocks/tab/tab.js

https://diane-tab-colors--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/tab

Fix tab colors

---

hlx_statics/blocks/info-card/info-card.css

Update the flexibility to have white background color. 
https://louisa-devsite-1413-sidekick-info-card--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/info-card

update the background color

---

hlx_statics/blocks/header/header.js
hlx_statics/scripts/lib-adobeio.js

Adding the dev environment https://developer-dev.adobe.com/events to include for the resolve in the header path.

Adding dev enviornment

---

hlx_statics/blocks/text/text.js

Cleanup the rest of metadata code in text component. 
https://main--adp-devsite--adobedocs.aem.page/test/hackathon/analytic/

code cleanup

---

hlx_statics/blocks/detailsblock/detailsblock.css
hlx_statics/blocks/detailsblock/detailsblock.js
hlx_statics/blocks/discoverblock/discoverblock.css
hlx_statics/blocks/heading2/heading2.css
hlx_statics/blocks/herosimple/herosimple.css
hlx_statics/blocks/herosimple/herosimple.js

**Fix :** Added background color in the hero simple block based on the props
**Test URL**
https://feat-details-block--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/
**Feat :** Added details block
**Test URL**
https://feat-details-block--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/
**Fix:** Design issues in the discover block
**Test URL**
https://feat-details-block--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/
**Fix:** Fix hover link in heading 2 
**Test URL** 
https://feat-details-block--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/zxp/resources

feat : details block

---

hlx_statics/blocks/announcement/announcement.js
hlx_statics/blocks/embed/embed.css
hlx_statics/blocks/heading3/heading3.css

Encounter alignment issues on the embed block
Previous : https://main--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/
Fix : https://embed-design-issues--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/
Fix : Button issues - Announcement block 
Test URL : https://embed-design-issues--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/zxp/distribution

fix : embed block design issues

---

hlx_statics/blocks/header/header.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/lib-helix.js
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

I fixed contrast, aria-labels, adding title to the page should help improve the accessibility for the pages. 
Before Score for accessibility is  78
After Score for accessibility is 93
https://devsite-1484-optimize-block--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/getting-started

Improve accessibility

---

hlx_statics/blocks/embed/embed.js
hlx_statics/blocks/header/header.css

Testing if this will improve the embed coiokie issue to cause the lighthouse score to be low. 
Changing the youtube server to use youtube-nocookie.com instead. 
https://devsite-1484-optimize-block--adp-devsite--adobedocs.aem.page/events/

changing to use youtube no cookie server to see

---

hlx_statics/blocks/header/header.css
hlx_statics/blocks/header/header.js
hlx_statics/blocks/info-columns/info-columns.css
hlx_statics/blocks/resource-card/resource-card.css
hlx_statics/blocks/side-nav/side-nav.css
hlx_statics/blocks/side-nav/side-nav.js
hlx_statics/blocks/table/table.css
hlx_statics/blocks/title/title.css
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js
package.json
yarn.lock

This PR improves the mobile navigation experience and fixes several UI issues related to the side navigation and menu behavior. Key changes include:
- Prevents body scrolling when the mobile menu is open
- Enhances mobile menu button handling for better responsiveness
- Fixes side navigation width and layout issues on mobile devices
- Improves grid template columns for better responsive layout
- Refactors side navigation initialization logic for better maintainability
- Cleans up navigation styles and template conditions
The side navigation system needed improvements to handle mobile views more gracefully and maintain consistency across different screen sizes. Also DevBiz (regular) and DevDocs (documentation) pages navigation needed consistency.
Tested on various screen sizes:
- Verified …

fix: Improve mobile navigation UX and prevent body scroll when menu is open

---

hlx_statics/blocks/header/header.js

Some changes in my previous PR to improve the accessibility scores got reverted.

changes got removed from other PR

---

hlx_statics/blocks/list/list.css
hlx_statics/blocks/list/list.js

Fixed the list block.
Test URL: https://fix-listblock--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
https://fix-listblock--adp-devsite--adobedocs.aem.page/github-actions-test/test/list-block

Fix listblock

---

hlx_statics/blocks/embed/embed.js
hlx_statics/scripts/delayed.js

Improve the embed component to add intersectionObserver to see if it improves the lighthouse score. 
https://louisa-devsite-1484--adp-devsite--adobedocs.aem.page/events/

update on embed

---

hlx_statics/blocks/tab/tab.css
hlx_statics/blocks/tab/tab.js

**Test URLs**
**DevBiz :** https://fix-tab-block-issue--adp-devsite--adobedocs.aem.page/test/melissa/modified-tabs
**DevDocs :** https://fix-tab-block-issue--adp-devsite--adobedocs.hlx.page/github-actions-test/test/tabs-block

Fix tab block issue

---

hlx_statics/scripts/scripts.js

I think this should be the way we load in config values like the redocly key or whatever.

feat: Add in function to load in config to window object

---

hlx_statics/blocks/announcement/announcement.css
hlx_statics/blocks/product-card/product-card.css
hlx_statics/blocks/summary/summary.css

Find some css is missing when running through all the components in sidekick library in order to prepare for go-live.

update on the css

---

hlx_statics/blocks/next-prev/next-prev.css
hlx_statics/blocks/next-prev/next-prev.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js

Added next previous page link 
Previous : https://developer-dev.adobe.com/developer-console/docs/guides/getting-started
Updated Test URL : https://next-prev-block--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/getting-started

Next Prev block

---

hlx_statics/blocks/announcement/announcement.css
hlx_statics/blocks/announcement/announcement.js
hlx_statics/blocks/herosimple/herosimple.css
hlx_statics/styles/styles.css

Previous: https://main--adp-devsite--adobedocs.aem.page/express/embed-sdk/docs/guides/
Current: https://fix-design-issues-baskar--adp-devsite--adobedocs.aem.page/express/embed-sdk/docs/guides/

Fix : Design issues - announcement , herosimple

---

hlx_statics/blocks/codeblock/codeblock.css

updating the border to now show up in the select box. 
Testing URL
https://louisa-devsite-1518-border--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon

update the focus border

---

hlx_statics/blocks/info-card/info-card.css

update on info card hover issue.
Previously: 
https://developer-stage.adobe.com/developer-champion/index-with-info-cards
After Fix:
https://louisa-devsite-1524-info-card-hover--adp-devsite--adobedocs.aem.page/developer-champion/index-with-info-cards

update info card hover issue

---

hlx_statics/blocks/discoverblock/discoverblock.css
hlx_statics/blocks/discoverblock/discoverblock.js

**Before:**
https://main--adp-devsite--adobedocs.aem.page/app-builder/docs/resources/blog-articles
https://main--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/
**After:**
test URL: https://bug-fix-discoverblock--adp-devsite--adobedocs.aem.page/app-builder/docs/resources/blog-articles
test URL: https://bug-fix-discoverblock--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/

fix: fixed discover block column and row design issue

---

hlx_statics/scripts/lib-helix.js

This just the code for normalizing the Path more clean and appending pathprefix to any relative paths. 
https://devsite-1519-normalizedpath--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/getting-started

normalizedPath

---

hlx_statics/blocks/mini-resource-card/mini-resource-card.css

Fixed design issues in mobile responsive 
Prev : https://main--adp-devsite--adobedocs.aem.page/express/add-ons/trending/
Updated : https://fixissue-mini-resource-card--adp-devsite--adobedocs.aem.page/express/add-ons/trending/

fix : design issues - mini-resource-card.css

---

hlx_statics/blocks/header/header.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/lib-helix.js

update the underline of top nav by using the selected sidenav for any document pages. 
currently: https://developer-dev.adobe.com/developer-console/docs/guides/getting-started
Fix: https://louisa-devsite-1512-top-nav--adp-devsite--adobedocs.aem.page/developer-console/docs/support/faq

underline the top nav correctly

---

hlx_statics/blocks/table/table.css
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

this is to update the dev docs to have whitebackground by default. 
https://devsite-1541-whitebackground--adp-devsite--adobedocs.aem.page/events/docs/guides/

update background to white background

---

hlx_statics/scripts/delayed.js

Adding a mouse over event over side-nav to start preload the pages.  
fixed:
https://devsite-1499-tableofcontent--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/plugins/plugin-distribution

update table of content with pre-load

---

hlx_statics/blocks/mini-resource-card/mini-resource-card.css

Change the spacing to 30px instead of 10px.
Old: 
https://developer-dev.adobe.com/test/hackathon/louisa/test-mini-resource-card
New:
https://devsite-1565-mini-card-space--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/test-mini-resource-card

update mini-resource-card space

---

hlx_statics/blocks/mini-resource-card/mini-resource-card.css
hlx_statics/blocks/summary/summary.css

realized the mini-resource-card needs to remove some bottom paddings and summary for top and bottom paddings. 
https://devsite-1554-layout-spacing--adp-devsite--adobedocs.aem.page/commerce/

layout fixes

---

hlx_statics/blocks/header/header.js
hlx_statics/blocks/side-nav/side-nav.css
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

The sideNav needs to correctly only render the subpages for it's active top nav.
Before:
Now:
https://devsite-1529-sidenav-page--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/

update on the sidenav

---

hlx_statics/scripts/lib-helix.js

https://devsite-1583-top-nave--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/getting-started/dev-tooling
Fix the issue where i'm making sure there's no leading and trailing slash.

Devsite 1583 top nav

---

hlx_statics/blocks/api-browser/api-browser.js

Api catalog path change

---

hlx_statics/blocks/announcement/announcement.css
hlx_statics/blocks/inlinealert/inlinealert.css
hlx_statics/blocks/inlinealert/inlinealert.js
hlx_statics/blocks/side-nav/side-nav.css
hlx_statics/scripts/lib-adobeio.js

https://devsite-1561-developer-distribute--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/submission/overview
Some colouring and padding issues in announcement and inline-alert. 
Old:
new:

update on minor coloring issues

---

hlx_statics/blocks/embed/embed.js

Fix : https://jira.corp.adobe.com/browse/DEVSITE-1580
Previous : https://main--adp-devsite--adobedocs.aem.page/github-actions-test/test/embed
Update : https://devsite-1580--adp-devsite--adobedocs.aem.page/github-actions-test/test/embed

Devsite 1580

---

hlx_statics/blocks/inlinealert/inlinealert.css
hlx_statics/blocks/inlinealert/inlinealert.js

https://jira.corp.adobe.com/browse/DEVSITE-1576
Fixed the inline-alert bugs as mentioned in devsite-1576.
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
Updated : https://devsite-1576--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon

fix : devsite-1576 inline-alert bugs.

---

hlx_statics/blocks/next-prev/next-prev.js
hlx_statics/blocks/side-nav/side-nav.js
hlx_statics/scripts/lib-helix.js

Issues : https://jira.corp.adobe.com/browse/DEVSITE-1613
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/getting-started/
Test URL : https://baskar-redirect--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/getting-started/

Next / Prev 

---

hlx_statics/blocks/footer/footer.css
hlx_statics/blocks/side-nav/side-nav.css
hlx_statics/scripts/lib-helix.js

Fixing the sidenav and the footer background color and small spacing issue.
Also fix the problem with the stage is not loading. 
Previously: 
https://developer-stage.adobe.com/developer-console/docs/guides/getting-started
With the fix:
https://devsite-1614-color-background--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/authentication/
match with prod
https://developer.adobe.com/developer-console/docs/support/

Fix sidenav and footer color

---

hlx_statics/scripts/lib-helix.js

the blank page issue caused by no link available but it's checking on the redirect.

fix the blank page issue.

---

hlx_statics/scripts/lib-helix.js

update the error handling to warning.

update error handling

---

hlx_statics/styles/styles.css

Fix: List height issues
The bullets have different line heights and look too compacted compared to the other text
Issue: https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
Preview: https://bug-fix-devsite-1578--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon

fix : list design issues - devsite-1578

---

hlx_statics/blocks/header/header.js
hlx_statics/scripts/scripts.js

the visibility change will affect the sidekick.  Will remove it for now until we revisit the improve performance on the sidenav.

fix sidekick

---

hlx_statics/blocks/header/header.js
hlx_statics/scripts/scripts.js

hotfix on sidekick to show up.  
Currently sidekick is not displaying.

updates on sidekick

---

hlx_statics/blocks/inlinealert/inlinealert.css
hlx_statics/styles/styles.css

https://jira.corp.adobe.com/browse/DEVSITE-1578
Fixed the updated bugs in devsite-1578
**Previous** : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/design/best-practices
**Test URL** : https://bug-fixes-devsite-1578--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/design/best-practices

Bug fixes devsite 1578

---

hlx_statics/blocks/accordion/accordion.css
hlx_statics/blocks/accordion/accordion.js
hlx_statics/blocks/announcement/announcement.css
hlx_statics/blocks/announcement/announcement.js
hlx_statics/blocks/api-browser/api-browser.css
hlx_statics/blocks/banner/banner.css
hlx_statics/blocks/cards/cards.css
hlx_statics/blocks/carousel/carousel.css
hlx_statics/blocks/code/code.css
hlx_statics/blocks/codeblock/codeblock.css
hlx_statics/blocks/columns/columns.css
hlx_statics/blocks/contributors/contributors.css
hlx_statics/blocks/detailsblock/detailsblock.css
hlx_statics/blocks/discoverblock/discoverblock.css
hlx_statics/blocks/embed/embed.css
hlx_statics/blocks/error404/error404.css
hlx_statics/blocks/header/header.css
hlx_statics/blocks/heading1/heading1.css
hlx_statics/blocks/heading2/heading2.css
hlx_statics/blocks/heading3/heading3.css
hlx_statics/blocks/hero/hero.css
hlx_statics/blocks/info-card/info-card.css
hlx_statics/blocks/info/info.css
hlx_statics/blocks/inlinealert/inlinealert.css
hlx_statics/blocks/list/list.css
hlx_statics/styles/styles.css

Remove container styles
https://jira.corp.adobe.com/browse/DEVSITE-1590
Before: https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
After: https://devsite-1590-remove-container-styles--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon

fix: remove container styles

---

hlx_statics/blocks/inlinealert/inlinealert.css

fix: inline alert design issues
previous: https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/addonsdk/
updated: https://fix-inlinealert-bug--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/addonsdk/
FYR: https://developer.adobe.com/express/add-ons/docs/references/addonsdk/

fix : inline alert bugs

---

hlx_statics/blocks/footer/footer.css
hlx_statics/blocks/header/header.css
hlx_statics/blocks/herosimple/herosimple.css
hlx_statics/blocks/onthispage/onthispage.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/styles/styles.css

- Align hero, body, and footer across all the breakpoints
https://jira.corp.adobe.com/browse/DEVSITE-1579
- https://devsite-1579-layout--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/support/
- https://devsite-1579-layout--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
- https://devsite-1579-layout--adp-devsite--adobedocs.aem.page/app-builder/docs/guides/
- https://devsite-1579-layout--adp-devsite-stage--adobedocs.aem.page/developer-console/docs/guides/
Sample hero in Gatsby: https://developer-stage.adobe.com/primetime/

fix: layout padding and alignment

---

hlx_statics/blocks/next-prev/next-prev.js

Fix : https://jira.corp.adobe.com/browse/DEVSITE-1660
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/
Updated : https://devsite-1660--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/

fix : next-prev - text content

---

hlx_statics/blocks/breadcrumbs/breadcrumbs.css
hlx_statics/blocks/side-nav/side-nav.css
hlx_statics/blocks/side-nav/side-nav.js
hlx_statics/styles/styles.css

Fix grid width and responsiveness
https://jira.corp.adobe.com/browse/DEVSITE-1579
https://stage--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
- https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
- https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/stats-addon
- https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/develop/coi
- https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
- https://devsite-1579-grid--adp-devsite-stage--adobedocs.aem.p …

fix: grid overflow

---

hlx_statics/blocks/header/header.css
hlx_statics/blocks/header/header.js

Currently:
https://stage--adp-devsite--adobedocs.aem.page/app-builder/
Fix:
https://devsite-1658-hover-tab--adp-devsite--adobedocs.aem.page/app-builder/

update the hover item

---

hlx_statics/blocks/heading3/heading3.css
hlx_statics/styles/styles.css

**Fix 1 :** Text color issue.
**Previous :** https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/classes/artboard-list
**Updated :** https://bug-fixes-text-design-issue--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/classes/artboard-list
**Fix 2 :** Added Text decoration for header link
**Previous :** https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/distribute/review-process/
**Updated :** https://bug-fixes-text-design-issue--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/distribute/review-process/

Bug fixes text design issue's

---

hlx_statics/blocks/header/header.css
hlx_statics/styles/styles.css

Fixes some of the header and content moving around when the page initially loads.
Test on:
https://perf-upgrade-2--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/
https://perf-upgrade-2--adp-devsite--adobedocs.aem.page/app-builder/

Fix header from jumping

---

hlx_statics/scripts/lib-helix.js

remove normalization
https://devsite-1629-navigation-fix--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/submission/overview

remove normalization

---

hlx_statics/blocks/side-nav/side-nav.js

Issue: 
https://stage--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/classes/unavailable-font
Will keep jumping back to the top when you try to goto a new page where the sidenav has scrolled to another position.
Fix: 
https://devsite-1545-sidenav--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/classes/unavailable-font
Storing the scrolltop location in local storage so when we load the sidenav again, it'll remember it.

Devsite 1545 sidenav jumpiing issue

---

hlx_statics/scripts/lib-adobeio.js

Align footer with main content
https://jira.corp.adobe.com/browse/DEVSITE-1605
- sidenav, no hero, onthispage: https://devsite-1685-footer-alignment--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/faq#what's-the-difference-between-the-creative-cloud-desktop-app-plugin-marketplace-and-exchange-marketplace
- sidenav, hero, no onthispage: https://devsite-1685-footer-alignment--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/
- no sidenav, no hero, no onthispage: https://devsite-1685-footer-alignment--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
- marketing on devdocs: https://devsite-1685-footer-alignment--adp-devsite--adobedocs.aem.page/developer-console/
- devbiz: …

fix: footer alignment

---

hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

previous:
https://main--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-badge
fix:
https://devsite-1693-badge--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-badge

update badge image

---

test/blocks/mini-resource-card/mini-resource-card.html
test/blocks/mini-resource-card/mini-resource-card.test.js
test/blocks/product-card/product-card.html
test/blocks/product-card/product-card.test.js
test/blocks/profile-card/profile-card.html
test/blocks/profile-card/profile-card.test.js

- profile-card.test.js
100% test coverage, no issues

profile-card test

---

test/blocks/mini-resource-card/mini-resource-card.html
test/blocks/mini-resource-card/mini-resource-card.test.js
test/blocks/product-card/product-card.html
test/blocks/product-card/product-card.test.js

- mini-resource-card.test.js
mini-resource-card.js:
- line 46: nobox-design class is no longer using, `block.classList.contains('nobox-design')`gets false and does not go through the if statement.
- line 49: primarybutton class is no longer using, `block.classList.contains('primarybutton'` gets false and does not go through the if statement.
- `getMiniResourceCard()` not tested

mini-resource-card test

---

test/blocks/link-block/link-block.html
test/blocks/link-block/link-block.test.js
test/blocks/product-card/product-card.html
test/blocks/product-card/product-card.test.js

- link-block.test.js
link-block.js:  
- line 13: `<li>` tag is no longer used in sample block, therefore `querySelector('li')` gets null and does not go through the forEach statement.
- line 26 - 27: sub-parent and link-block-wrapper are no longer used in sample block, `querySelector(.link-block-wrapper)` gets null and does not go through the `if (linkBlockWrapper)` statement

link-block test

---

hlx_statics/blocks/columns/columns.css
hlx_statics/blocks/columns/columns.js

1. Align the content within the columns block horizontally with the align property.
https://jira.corp.adobe.com/browse/DEVSITE-1753
Previous : https://main--adp-devsite--adobedocs.aem.page/test/baskar/coloumns
Updated : https://fix-columns-issue--adp-devsite--adobedocs.aem.page/test/baskar/coloumns

fix : columns issues

---

test/blocks/info-columns/info-columns.html
test/blocks/info-columns/info-columns.test.js
test/test.md

- `info-columns.test.js`
- info-column does not use `<p>` tag anymore, so querySelector.forEach will not run through
- `querySelectorAll('div > div.info-column')` is placed inside info-column's forEach statement so will get null

info-column test

---

hlx_statics/blocks/image-text/image-text.css
hlx_statics/blocks/image-text/image-text.js

For the Imaget text component, request a center button that will allow teams to create a call to action button that is centered below the component.
https://jira.corp.adobe.com/browse/DEVSITE-1771
Previous : https://main--adp-devsite--adobedocs.aem.page/test/baskar/image-text-block
Updated : https://fix-image-text-block--adp-devsite--adobedocs.aem.page/test/baskar/image-text-block

update : center button - image-text block

---

hlx_statics/blocks/announcement/announcement.js

Encountered background color issues in the Announcement block on the Dev Biz.
Updated the background color based on the class name.
https://jira.corp.adobe.com/browse/DEVSITE-1760
Previous : https://stage--adp-devsite--adobedocs.aem.page/test/baskar/coloumns
Updated : https://fix-announcement-bgcolor--adp-devsite--adobedocs.aem.page/test/baskar/coloumns
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/distribute/guidelines/general/listing
Updated : https://fix-announcement-bgcolor--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/distribute/guidelines/general/listing

fix : background color issues - devbiz

---

hlx_statics/blocks/product-card/product-card.css
hlx_statics/blocks/product-card/product-card.js

I encountered issues with the product card during the add-ons migration. I've fixed them in the test repo and created three types to handle the possible ways the code might appear in the md file.
Product design issues - Docs (https://jira.corp.adobe.com/browse/DEVSITE-1745)
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/product-card
Updated : https://fix-product-card--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/product-card
Previous : https://stage--adp-devsite--adobedocs.aem.page/test/baskar/product-card
Updated : https://fix-product-card--adp-devsite--adobedocs.aem.page/test/baskar/product-card

fix : product-card design issues

---

hlx_statics/blocks/cards/cards.js
test/blocks/cards/cards-fourCards.html
test/blocks/cards/cards-threeCards.html
test/blocks/cards/cars.test.js
test/test.md

- card.test.js
- the decorate function performs differently between browser `aem up` and node.js `npm run test`
- in browser, the target div (line 60 in card.js) is the direct second child of "three-card" div
- in node test, the target div is the direct second grandchild of "three-card" div
- line 58 - 62 can be safely deleted without effecting any display

Cards test

---

hlx_statics/blocks/discoverblock/discoverblock.css
hlx_statics/blocks/discoverblock/discoverblock.js
hlx_statics/scripts/lib-adobeio.js

Neede to rewrite most of this component to make the discover block with image, text and links to display correct. 
I've also created some test pages.
https://devsite-1750-discoverblock--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-discoverblock
https://devsite-1750-discoverblock--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-discover-2
https://devsite-1750-discoverblock--adp-devsite--adobedocs.aem.page/data-collection-apis/docs/support
https://devsite-1750-discoverblock--adp-devsite--adobedocs.aem.page/app-builder/docs/resources/videos/

Devsite 1750 discoverblock for image 

---

dev.mjs
package.json

Adding in devmode scripts. There's still more work to do on the scripts but I needed the latest stuff on stage for my stuff to work.

Adding in devmode

---

hlx_statics/blocks/resources/resources.css
hlx_statics/blocks/resources/resources.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js
hlx_statics/styles/styles.css

Adding the resources component  
Previously:
https://main--adp-devsite--adobedocs.aem.page/data-collection-apis/docs/
After Fix:
https://devsite-1722-resources-component--adp-devsite--adobedocs.aem.page/data-collection-apis/docs/

adding resources component for devdocs

---

hlx_statics/blocks/mini-resource-card/mini-resource-card.js

Fix design issue - mini resource card
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/
Update  : https://mini-resources-design-issue--adp-devsite--adobedocs.aem.page/express/

fix : mini resource card issue

---

hlx_statics/blocks/carousel/carousel.js
test/blocks/carousel/carousel.html
test/blocks/carousel/carousel.test.js
test/test.md

- carousel.test.js
- fixed carousel.js id issue
- tested arrow onClick event
- tested touch event on mock mobile

carousel test done

---

test/blocks/table/table.html
test/blocks/table/table.test.js

table block test

---

hlx_statics/blocks/hero/hero.css
hlx_statics/blocks/hero/hero.js
hlx_statics/blocks/herosimple/herosimple.js

Added video in hero & hero simple
https://jira.corp.adobe.com/browse/DEVSITE-1846
**DevBiz**
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/
Updated : https://baskar-video-poc--adp-devsite--adobedocs.aem.page/express/add-ons/
**DevDocs**
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/product-card
Updated : https://baskar-video-poc--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/product-card

Hero block

---

hlx_statics/scripts/scripts.js

- **Issue:** Hero images on EDS are blurrier compared to Gatsby
- **Fix:** Overwrite EDS image optimization to get sharper Hero images similar to Gatsby
Chris suggested to turn down compression and bump up resolution to prevent oversampling: https://adobeio.slack.com/archives/CGD27G7LL/p1752519653501579?thread_ts=1752519275.411859&cid=CGD27G7LL
However, I found by experimentation that setting `optimize=low` and bumping up resolution (from say `?width=2000` to `?width=2500`) wasn't enough. 
So I removed the breakpoint modifiers (e.g. width, height, media) altogether to ensure high-fidelity. This will allow product teams to control the resolution via the image they supply. It will then also be up to them to ensure they don't upload ginormous files that will slow down the site.
While …

feat: overwrite EDS hero image optimization

---

hlx_statics/styles/styles.css

Font Size Mismatch
https://jira.corp.adobe.com/browse/DEVSITE-1852
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/
Update : https://fontsize-mismatch--adp-devsite--adobedocs.aem.page/express/add-ons/

fix : font size mismatch

---

hlx_statics/blocks/columns/columns.css
hlx_statics/blocks/columns/columns.js

Columns Block messy
https://jira.corp.adobe.com/browse/DEVSITE-1853
**DevBiz** 
Previous : https://stage--adp-devsite--adobedocs.aem.page/test/baskar/coloumns
Update : https://columns-messy--adp-devsite--adobedocs.aem.page/test/baskar/coloumns
**DevDocs - No issue**
Previous : https://stage--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-hero
Update : https://columns-messy--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-hero

Columns messy

---

hlx_statics/blocks/site-wide-banner/site-wide-banner.js

Adding in some more logic in how to handle the site wide banner when it exists or not. 
This is a bit tricky to test as it involves things existing on the prod env or not. Hopefully it works when deployed *crosses fingers*

fix: site wide banner showing logic

---

hlx_statics/blocks/columns/columns.js
hlx_statics/blocks/info-columns/info-columns.js
hlx_statics/scripts/lib-adobeio.js
hlx_statics/scripts/scripts.js

Link doesn’t open in a new tab
https://jira.corp.adobe.com/browse/DEVSITE-1857
**DevBiz**
Previous : https://stage--adp-devsite--adobedocs.aem.page/express/embed-sdk/
Update : https://external-link--adp-devsite--adobedocs.aem.page/express/embed-sdk/
**DevDocs**
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/test-hr-0
Update : https://external-link--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/test-hr-0
MD file : https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/test-hr-0.md?plain=1
**Test URL for columns & info-block**
https://external-link--adp-devsite--adobedocs.aem.page/test/baskar/tab

fix : external links open in new tab

---

test/blocks/list/list.html
test/blocks/list/list.test.js
test/test.md

- **list>js**
- line 25 - 43
- `getMetadata('template')` is null

list block test done

---

test/blocks/tab/tab.html
test/blocks/tab/tab.test.js
test/test.md

- **tab.js**
- line 27 - 31:
- Function `handleCode()` branch for `if (codeBlock && !isTable)` not covered
- The google drive example does not have a code block without a table
- line 85 - 87:
- `getMetadata('template')` gets null

tab block test done

---

dev.mjs
hlx_statics/blocks/fragment/fragment.js

This fixes when trying to load a site in local dev mode without having to upload the config.md file first. 
To test, run this in local dev mode along with the runtime connector and a content repo. Update the `src/pages/config.md` in the content repo and see if updates locally.

Fix config loading locally in local dev mode

---

dev.mjs

The local dev mode should now point to the stage version of the devsite paths to read in which path prefixes are configured.

Fetch from devsitepaths in google drive and fix up how it matches paths

---

hlx_statics/blocks/superhero/superhero.css
hlx_statics/blocks/superhero/superhero.js

Merge `DevBiz Hero (default)` as `DevBiz Superhero (halfwidth)`
https://jira.corp.adobe.com/browse/DEVSITE-1756
Notice that
- Google doc only changes the block name and variant
- Page looks the same
| | DevBiz Hero (default) | DevBiz Superhero (halfwidth) |
| --- | --- | --- |
| Google doc | https://docs.google.com/document/d/1dcdvp9cy1QoWuNtTB6roR3A6y-o0k73TJP_4dsHtZPw/edit?tab=t.0 | https://docs.google.com/document/d/1B4Rjhkhlk3Hc7ce6mRtT1KYr0qCmby8ut3S_bxG2Aoo/edit?tab=t.0 |
| Page | https://superhero-from-devbiz-hero--adp-devsite--adobedocs.aem.page/test/melissa/superhero/old/hero-default?nocache=1757429145510 | https://superhero-from-devbiz-hero--adp-devsite--adobedocs.aem.page/test/melissa/superhero/new/hero-default?nocache=1757690545196 |
| | DevBiz Hero (default) | DevBiz …

feat: merge devbiz hero into superhero

---

hlx_statics/scripts/lib-helix.js

Fix: Don’t encode/decode angle brackets within a code block

Fix code format issue
