- hlx_statics/blocks/side-nav/side-nav.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
- Refactor to prep for adding breadcrumbs
- Set up breadcrumbs layout so that it is on top of `gridAreaMain` and next to `gitHubActions`:
Test link: https://breadcrumbs-layout--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/getting-started
> Breadcrumbs layout

- hlx_statics/blocks/onthispage/onthispage.js
I found an issue in the "OnThisPage" section. In the existing implementation, we were taking h2 and h3 tags from the main container, which in some cases included tags from the footer as well, which we don’t need. I have fixed that and created a PR. Kindly review it.
> fix : fixed the issue of taking content from footer

- hlx_statics/blocks/breadcrumbs/breadcrumbs.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/styles/styles.css
**Ticket:** https://jira.corp.adobe.com/browse/DEVSITE-1233
**Description:** Hide breadcrumbs if there's a hero block on the page or if hideBreadcrumbsNav config is set to true
**Test:**
- without hero, without config -> show breadcrumbs
- md: https://github.com/AdobeDocs/adobe-dev-console/blob/main/src/pages/guides/authentication/UserAuthentication/implementation.md?plain=1#L1
- page: https://hide-breadcrumbs--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/authentication/UserAuthentication/implementation
- without hero, with config -> hide breadcrumbs
- md: https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/index.md?plain=1#L2
- page: https://hide-breadcrumbs--adp-devsite--adobedocs.hlx.page/github-actions-test/test/
- with hero, without …
> Hide breadcrumbs based on hero and config

- hlx_statics/blocks/table/table.css
https://jira.corp.adobe.com/browse/DEVSITE-1292
https://main-overlaps-with-onthispage--adp-devsite--adobedocs.hlx.page/developer-console/docs/guides/authentication/UserAuthentication/
> fix: prevent main from overlapping with onthispage

- hlx_statics/blocks/redoclyapiblock/redoclyapiblock.js
- hlx_statics/scripts/lib-adobeio.js
https://jira.corp.adobe.com/browse/DEVSITE-1241
The EDS counterpart of Gatsby's [RedoclyAPIBlock](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js)
Differences from Gatsby:
- In Gatsby, secrets were accessed during the [deploy process](https://github.com/AdobeDocs/redocly-test/blob/main/.github/workflows/deploy.yml#L129) and [env](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js#L18). For EDS, this is something we still need to figure out.
- Attributes from markdown were passed as rows by the `devsite-runtime-connector` ([#18](https://github.com/aemsites/devsite-runtime-connector/pull/18), [#19](https://github.com/aemsites/devsite-runtime-connector/pull/19), …
> feat: redoclyapiblock

- hlx_statics/blocks/code/code.css
- hlx_statics/blocks/code/code.js
- hlx_statics/blocks/codeblock/codeblock.css
- hlx_statics/blocks/codeblock/codeblock.js
- hlx_statics/blocks/tab/tab.css
- hlx_statics/blocks/tab/tab.js
- hlx_statics/components/code.js
- hlx_statics/scripts/delayed.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/prism.css
- hlx_statics/styles/styles.css
Ticket: 
https://jira.corp.adobe.com/browse/DEVSITE-1454
Test URLs : 
- code nested in list: https://fix-code-block-issue--adp-devsite--adobedocs.aem.page/app-builder/docs/guides/application-logging/azure-log-analytics
- code: https://fix-code-block-issue--adp-devsite--adobedocs.aem.page/github-actions-test/test/code
- code block (known issue with connector stripping out code language): https://fix-code-block-issue--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/codeblock
- tab: https://fix-code-block-issue--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/tab
- redocly api block (known issue with license not allowed on PR branches):  https://fix-code-block-issue--adp-devsite--adobedocs.aem.page/github-actions-test/test/redocly-api-block
Issue: 
EDS doesn't allow for blocks …
> Fix code block issue

- hlx_statics/scripts/lib-adobeio.js
Old code got reintroduced in a PR intended to fix breadcrumbs:
- from third commit where `one-repo` was merged to the PR's branch: https://github.com/AdobeDocs/adp-devsite/pull/33/commits
- the unintended merge: https://github.com/AdobeDocs/adp-devsite/pull/33/files#diff-e09b42e560eecc65cd532c29d6e08f7914959673b6070af5633e95cc70adaff0R200-R219
This causes regression on code block issue fix:
- from this PR where it was relying on `buildCodes` to be: https://github.com/AdobeDocs/adp-devsite/pull/29/files#diff-e09b42e560eecc65cd532c29d6e08f7914959673b6070af5633e95cc70adaff0R208-R216
Undo unintended merge
> undo merge conflict

- hlx_statics/blocks/code/code.css
- hlx_statics/scripts/lib-adobeio.js
https://jira.corp.adobe.com/browse/DEVSITE-1454
`decoratePreformattedCode` was grabbing the wrong `<code>` within the container
Wrap `<pre><code>` in `nested-code-wrapper` so that `decoratePreformattedCode` grabs the correct `<code>`
- url: https://fix-nested-codes--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation
- compare to prod: https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation/
> fix: nested codes

- hlx_statics/scripts/lib-adobeio.js
Problem: Some random code blocks are injected as inline alert. 
Solve:  The problem is building code is getting the wrong parentElement to replace with the building code.  Because the inline alert also have PRE element, it selected the wrong element to replace the code block.  Now I used the correct element as the replacement block, it resolved the issues. 
Before:
Now:
https://louisa-devsite-1463-code--adp-devsite--adobedocs.aem.page/events/docs/guides/#troubleshooting-unstabledisabled-registration-status
> Inline alert with coding blocks.

- hlx_statics/blocks/redoclyapiblock/redoclyapiblock.js
https://jira.corp.adobe.com/browse/DEVSITE-1241
Parse attributes from the block's `<div>` (added in https://github.com/AdobeDocs/adp-devsite/pull/37)
1. Run adp-devsite locally (because redocly license doesn't work on test branch)
2. Go to http://localhost:3000/github-actions-test/test/redocly-api-block
3. Inspect
4. CTRL+F for `RedoclyReferenceDocs.init`
5. Confirm the attributes defined in the markdown file are passed to Redocly: https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/redocly-api-block.md?plain=1#L6-L22
> Parse RedoclyAPIBlock attributes

- hlx_statics/blocks/breadcrumbs/breadcrumbs.css
- hlx_statics/blocks/inline-nested-alert/inline-nested-alert.css
- hlx_statics/blocks/inline-nested-alert/inline-nested-alert.js
- hlx_statics/blocks/inlinealert/inlinealert.css
- hlx_statics/blocks/inlinealert/inlinealert.js
- hlx_statics/styles/prism.css
- hlx_statics/styles/styles.css
1. On some pages, page scrolling occurred due to the code block and content header, so I have fixed that.
2.  In the documentation, the variants were not being applied at this [line](https://github.com/AdobeDocs/adp-devsite/blob/2772ec02ba801ea0ecb0d710b14469478679218a/hlx_statics/blocks/inlinealert/inlinealert.js#L61), so I have added this condition.
**Test URl** : https://fix-inline-alert--adp-devsite--adobedocs.aem.page/events/docs/guides/using/aem/aem-addon-module/
> Fix inline alert

- hlx_statics/blocks/discoverblock/discoverblock.css
- hlx_statics/blocks/discoverblock/discoverblock.js
- hlx_statics/blocks/inlinealert/inlinealert.css
- hlx_statics/blocks/inlinealert/inlinealert.js
- hlx_statics/blocks/link-block/link-block.css
- hlx_statics/blocks/link-block/link-block.js
- hlx_statics/blocks/table/table.css
The "Discover" block was not displaying properly, so I have fixed it.
Before: https://main--adp-devsite--adobedocs.aem.page/app-builder-template-registry/
After: https://fix-discover-link--adp-devsite--adobedocs.aem.page/app-builder-template-registry/
I removed the table's width: 100vw style to control the page scroll.
The Inlinealert block was creating multiple blocks, which I have now fixed.
Before: https://main--adp-devsite--adobedocs.aem.page/events/docs/guides/api/eventsingress-api
After: https://fix-discover-link--adp-devsite--adobedocs.aem.page/events/docs/guides/api/eventsingress-api
Link-Block Added: https://fix-discover-link--adp-devsite--adobedocs.aem.page/app-builder-template-registry/
> fix: fixed discover block && inline alert block

- hlx_statics/components/code.js
The code language is already added as classname so we don't need to read the code from the code block anymore. 
The code block should already work.  Removing the unneeded code as cleanup.
> removing the unnecessary code

- hlx_statics/blocks/code/code.js
- hlx_statics/blocks/detailsblock/detailsblock.css
- hlx_statics/blocks/herosimple/herosimple.js
- hlx_statics/styles/styles.css
1. Fixed the hero-simple section to properly set the background image and added responsiveness.
Before: https://main--adp-devsite--adobedocs.aem.page/app-builder/docs/overview/
After: https://fix-detailsblock--adp-devsite--adobedocs.aem.page/app-builder/docs/overview/
2. Added the width for the nested-code block.
3.  code block.
In some cases, if the language is not specified for a code block, it gets converted to a code block but doesn't produce the desired output. So, I have set bash as the default language. Let me know if this is fine or if it should be handled differently.
E.g: https://github.com/AdobeDocs/app-builder/blob/7601d31f46c308aa0664da8cb6bf2ebb9f5ba311/src/pages/guides/extensions/extension-migration-guide.md?plain=1#L98
Before: …
> fix: herosimple, details and code block

- hlx_statics/blocks/redoclyapiblock/redoclyapiblock.js
Retrieve redocly license key from [config](https://github.com/AdobeDocs/adp-devsite/pull/70)
https://jira.corp.adobe.com/browse/DEVSITE-1241
Tested locally (http://localhost:3000/github-actions-test/test/redocly-api-block)
Can't test on branch (https://main--adp-devsite--adobedocs.hlx.page/github-actions-test/test/redocly-api-block) because that domain isn't in the list of allowed domains for Redocly on-premise license key. But once merged to main, can test on dev (https://developer-dev.adobe.com/github-actions-test/test/redocly-api-block)
> retrieve redocly license key from config

- hlx_statics/blocks/header/header.js
- hlx_statics/blocks/side-nav/side-nav.js
Fix missing decoration for global navigation nested links.
Refactored duplicate decoration function for global nav.
Testing url: https://missing-nav-dropdown-fix--adp-devsite--adobedocs.aem.page/github-actions-test/test/code-block
> Missing nav dropdown fix

- hlx_statics/blocks/banner/banner.css
- hlx_statics/blocks/discoverblock/discoverblock.css
the discoverblock in the dev docs side is not properly aligned with the previous fix with the wrapper css changes.  
Another issue is fixed when I was checking on the banner in mobile view.  
Previous:
https://developer-dev.adobe.com/developer-console/docs/guides/
Now: 
https://louisa-bug-fixes--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/
> Fix docs issue with discoverblock

- hlx_statics/blocks/header/header.js
- hlx_statics/blocks/side-nav/side-nav.js
Use `source` instead of `template` metadata for nav source selection.
Testing urls: 
https://fix-nav-origin-select--adp-devsite--adobedocs.aem.page/github-actions-test/
https://fix-nav-origin-select--adp-devsite--adobedocs.aem.page/
https://fix-nav-origin-select--adp-devsite--adobedocs.aem.page/github-actions-test/
> Fix: use source metadata to select config or nav file for navigation

- hlx_statics/blocks/codeblock/codeblock.css
- hlx_statics/blocks/codeblock/codeblock.js
https://jira.corp.adobe.com/browse/DEVSITE-1495
Implement the code block picklist as described in the [aio theme readme](https://github.com/adobe/aio-theme?tab=readme-ov-file#code-block):
> Use `languages` to define a language name for each code section. Code sections with the same heading are automatically grouped together. The number of languages should match the number of headings. If no language is present, each of the heading will render in each tab with even the same headings.
- Ensured the number of tabs, panels, and options always match
- Mapped tabs, panels, and options are via indices
- Hid tabs, panels, and options are based on current selection 
- code block with picklist 
- page: https://code-block-picklist--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials …
> feat: code block picklist

- hlx_statics/blocks/columns/columns.css
The header font size is not displaying properly.
Adding the correct font-size for headers. 
Previous: 
https://developer-stage.adobe.com/cpp-docs/careers/index-onerepo
After Fix:
https://louisa-devsite-1521-column-header--adp-devsite--adobedocs.aem.page/cpp-docs/careers/index-onerepo
> Fix Header font size

- hlx_statics/blocks/code/code.js
- hlx_statics/blocks/heading1/heading1.js
- hlx_statics/blocks/tab/tab.js
- hlx_statics/components/code.js
https://jira.corp.adobe.com/browse/DEVSITE-1514
Code block in list isn't decorated
Language wasn't specified, and so prism didn't syntax highlight because it was expecting `language-*` class in `code`
Ensured `language-none` is set if language isn't specified
- removed unused import statement
- guarded against null
- moved setting of `language-none` to one place
https://fix-nested-code--adp-devsite--adobedocs.aem.page/developer-console/docs/guides/authentication/JWT/jwt-certificate
- https://fix-nested-code--adp-devsite--adobedocs.aem.page/github-actions-test/test/code
- https://fix-nested-code--adp-devsite--adobedocs.aem.page/github-actions-test/test/code-block
> fix: nested code

- hlx_statics/blocks/info-card/info-card.css
The issue was the info card is limited to 400px and that makes the gap doesn't fit into the whole 1280px width.  I've increased the gap to fit for the width. 
Fix: 
https://louisa-devsite-1460-infocard--adp-devsite--adobedocs.aem.page/commerce/
> Update info card css to match other components

- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
Adding a nobox design for flexibility for some marketing pages. 
https://devsite-1544-mini-resource-card--adp-devsite--adobedocs.aem.page/test/hackathon/louisa/test-mini-resource-card
> adding a nobox-design for the miniresource cards

- hlx_statics/blocks/mini-resource-card/mini-resource-card.css
- hlx_statics/blocks/mini-resource-card/mini-resource-card.js
fix : mini-resource-card responsive design issue
previous : https://main--adp-devsite--adobedocs.aem.page/express/add-ons/trending/
updated : https://fix-mini-resource-card--adp-devsite--adobedocs.aem.page/express/add-ons/trending/
found a mistake in the mini-resource card. In the mobile responsive view, when the text is large, the padding gets reduced. So, we need to add padding specifically for mobile responsiveness
> fix : mini-resource-card responsive design issue

- hlx_statics/blocks/site-hero/site-hero.js
https://devsite-1560-site-hero-text--adp-devsite--adobedocs.aem.page/developers-live/
Fix the bug where the text is reverted.
> site hero bug fix

- hlx_statics/styles/styles.css
https://jira.corp.adobe.com/browse/DEVSITE-1578
fix : worked out the bugs in devsite-1578 related to paragraph line-height and inline code size issues.
previous  :  https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
updated :  https://devsite-1578--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
> fix : devsite-1578 style bugs in paragraph and inline-code issue.

- hlx_statics/blocks/codeblock/codeblock.js
https://jira.corp.adobe.com/browse/DEVSITE-1575
fix : worked out & fix  code blocks don't show tabs properly in on-load & their codes.
previous  : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
updated  : https://devsite-1575--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/grids-addon
> fix : DEVSITE- 1575 CodeBlock Loading issue

- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
Point our analytics test suite to the aep version. 
Test on:
https://aep-analytics--adp-devsite--adobedocs.aem.page/
Should load the js lib: https://www.adobe.com/marketingtech/main.standard.min.js
And `_satellite` should be available in the console in the web inspector.
Also, clicking any links should send a network request to:
https://sstats.adobe.com/ee/or2/v1/collect?configId=...
> Add in AEP Analytics

- hlx_statics/blocks/onthispage/onthispage.css
https://jira.corp.adobe.com/browse/DEVSITE-1579
Changes to `onthispage`:
- Hide when it doesn't fit the screen
- Make width match `side-nav`'s
- Add a right margin equal to the left
URL for testing:
- https://devsite-1579-responsive-onthispage--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/submission/overview
If screen too narrow to fit `onthispage`, you can scroll to the right to see squished `onthispage`:
If screen too narrow to fit `onthispage`, `onthispage` gets hidden and no horizontal scrollbar appears:
> Hide onthispage when it doesn't fit

- hlx_statics/blocks/accordion/accordion.css
- hlx_statics/blocks/code/code.css
- hlx_statics/blocks/discoverblock/discoverblock.css
- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/inlinealert/inlinealert.css
- hlx_statics/blocks/table/table.css
- hlx_statics/styles/styles.css
Original spacing fix was applied to `section` to ensure spacing is consistent across all blocks. This worked when each block are in their own section. While this is the case with our DevBiz pages today, user is still allowed to add multiple blocks within a section. In DevDocs, the original spacing fix doesn't work because all blocks are in the same section.
- Refactor spacing fix so that it's applied to the block  (i.e. wrapper) rather than section (i.e. container) - [DEVSITE-1590](https://jira.corp.adobe.com/browse/DEVSITE-1590)
- Ensure spacing is consistent across blocks - [DEVSITE-1554](https://jira.corp.adobe.com/browse/DEVSITE-1554)
- https://devsite-1590-block-spacing--adp-devsite--adobedocs.aem.page/test/diane/devsite-1415-background-color
- …
> fix: block spacing

- hlx_statics/blocks/info-card/info-card.css
previously:
https://developer-stage.adobe.com/commerce/
fixed:
https://devsite-1581-fix--adp-devsite-stage--adobedocs.aem.page/commerce/
https://devsite-1581-fix--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/guides/tutorials/
reverted the image ratio to match what we have in prod for now.
> update info card for dev biz

- hlx_statics/blocks/columns/columns.css
- hlx_statics/blocks/summary/summary.css
- hlx_statics/blocks/summary/summary.js
- hlx_statics/scripts/lib-adobeio.js
Fix for these issues: https://jira.corp.adobe.com/browse/DEVSITE-1555 and https://jira.corp.adobe.com/browse/DEVSITE-1556
Columns image was distorting when window size got smaller and summary block height was not increasing to 500px when window size was smaller. Summary block was also not working correctly for blocks with no images so fixed that too
Before: https://main--adp-devsite--adobedocs.aem.page/test/diane/devsite-1556-resize-columns
After: https://resize-blocks--adp-devsite--adobedocs.aem.page/test/diane/devsite-1556-resize-columns
Doc: https://docs.google.com/document/d/15EcvIpD4Rb-K8oaBeJPkyDXdYvhA0FaRrZ-7_iHRpoU/edit?tab=t.0
> Fixed resize issue for blocks column and summary

- hlx_statics/blocks/columns/columns.css
**Description**
Fix selector so that checkmark bulletpoints get shown when specified by user
**Test Google doc**
https://docs.google.com/document/d/1fKHTmZ8G_SDcxMBM3r03w-KYUONw53eSP78ZRn4Lok8/edit?tab=t.0
**Before**
https://stage--adp-devsite--adobedocs.aem.page/test/melissa/columns?nocache=1743631853759
**After**
https://column-checkmark--adp-devsite--adobedocs.aem.page/test/melissa/columns?nocache=1743631853759
> fix: column checkmark

- hlx_statics/blocks/info-card/info-card.css
Fix: https://diane-info-rm-background--adp-devsite--adobedocs.aem.page/test/diane/devsite-1644-info-card-background-color
Current: https://main--adp-devsite--adobedocs.aem.page/test/diane/devsite-1644-info-card-background-color
https://jira.corp.adobe.com/browse/DEVSITE-1644
> Remove background color from image portion of info card

- hlx_statics/blocks/contributors/contributors.css
- hlx_statics/blocks/contributors/contributors.js
- hlx_statics/blocks/discoverblock/discoverblock.css
- hlx_statics/blocks/embed/embed.css
- hlx_statics/blocks/embed/embed.js
- hlx_statics/blocks/herosimple/herosimple.css
- hlx_statics/blocks/iframe/iframe.css
- hlx_statics/blocks/image-text/image-text.css
- hlx_statics/blocks/image-text/image-text.js
- hlx_statics/components/wrapperContainer.js
- hlx_statics/styles/styles.css
https://jira.corp.adobe.com/browse/DEVSITE-1590
We decided on an approach where we merge styles from `container` (shared) to `wrapper` (not shared). However that doesn't work for some blocks that need style applied to a parent div.
This PR inserts a div between `container` and `wrapper` called a `wrapper-container`, and merge styles from `container` (shared) to `wrapper-container` (not shared).
URL for testing:
- https://devsite-1590-insert-container-styles--adp-devsite--adobedocs.aem.page/test/contributors
- https://devsite-1590-insert-container-styles--adp-devsite--adobedocs.aem.page/developer-distribution/experience-cloud/docs/guides/
- https://devsite-1590-insert-container-styles--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/embed
- …
> fix: insert container styles

- hlx_statics/blocks/herosimple/herosimple.js
- hlx_statics/blocks/side-nav/side-nav.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
- Move layout logic out of `herosimple` and `sidenav` blocks
- Fix `herosimple` width issue when no `sidenav`
- Remove `herosimple` container style
- https://jira.corp.adobe.com/browse/DEVSITE-1590
- https://jira.corp.adobe.com/browse/DEVSITE-1625
- https://devsite-1590-refactor-layout--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
- https://devsite-1590-refactor-layout--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/support/
- https://devsite-1590-refactor-layout--adp-devsite-stage--adobedocs.aem.page/developer-distribution/experience-cloud/docs/guides/
- https://devsite-1590-refactor-layout--adp-devsite--adobedocs.aem.page/app-builder/docs/guides/
> fix: layout

- hlx_statics/blocks/embed/embed.js
- hlx_statics/scripts/lib-helix.js
currently:
https://developer-stage.adobe.com/developer-distribution/creative-cloud/docs/guides/zxp/distribution
https://developer-stage.adobe.com/developer-distribution/creative-cloud/docs/guides/submission/overview
https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/
with fix:
https://devsite-1584-color-consistency--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/zxp/distribution
https://devsite-1584-color-consistency--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/submission/overview
https://devsite-1584-color-consistency--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/
> update all document components should have white background

- hlx_statics/blocks/inlinealert/inlinealert.css
- hlx_statics/styles/styles.css
- Fixed text-decoration issue for links inside the **inline-alert** component  
- Addressed text-decoration and styling issues for anchor tags 
**Previous :** https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/getting-started/quickstart
**Updated :** https://fix-add-ons-design-issue--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/getting-started/quickstart
- Resolved underline issue on button text when hovered  
**Previous** : https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/distribute/guidelines/general/listing
**Updated :**https://fix-add-ons-design-issue--adp-devsite--adobedocs.aem.page/express/add-ons/docs/guides/distribute/guidelines/general/listing
> fix : bug fixes in add-ons

- hlx_statics/scripts/scripts.js
Add in page tracking by calling the ` _satellite.track()`.
Test on page on:
https://analytics-track-page--adp-devsite-stage--adobedocs.aem.page/
Check console.log to display:
```
Route tracking page name as: <page location>
```
> Track page on load

- hlx_statics/blocks/footer/footer.css
Fix footer width and responsiveness
https://jira.corp.adobe.com/browse/DEVSITE-1579
https://devsite-1579-footer--adp-devsite--adobedocs.aem.page/test/accordion
https://devsite-1579-footer--adp-devsite--adobedocs.aem.page/tools/sidekick/blocks/api-browser
> fix: footer width and responsiveness

- hlx_statics/blocks/side-nav/side-nav.css
Make collapse animation start from the right edge of the sidenav, rather than the right edge of the entire window.
https://jira.corp.adobe.com/browse/DEVSITE-1650
https://stage--adp-devsite-stage--adobedocs.aem.page/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration
https://devsite-1650--adp-devsite-stage--adobedocs.aem.page/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration
> fix: sidenav collapse animation width

- hlx_statics/styles/styles.css
Fix : inline-code font design bug inside the header-content
**Previous URL :** https://stage--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/type-aliases/font
**Updated URL :**  https://bug-fix-inline-code-design--adp-devsite--adobedocs.aem.page/express/add-ons/docs/references/document-sandbox/document-apis/type-aliases/font
> fix : inline-code design issue

- hlx_statics/blocks/announcement/announcement.css
- hlx_statics/blocks/announcement/announcement.js
- hlx_statics/blocks/columns/columns.css
Width resizes down to 75% when in tablet view which really helps when columns have lists and fixed images resizing for now reason in tablet view. Also changed word break behavior in announcement block to the behavior that every other block has: Smaller widths cause entire words to drop to the next line, but the words aren't split up.
Before: https://main--adp-devsite--adobedocs.aem.page/test/diane/devsite-1558-columns-width
Before stage: https://stage--adp-devsite--adobedocs.aem.page/test/diane/devsite-1558-columns-width
Fix: https://diane-ticket-57-58--adp-devsite--adobedocs.aem.page/test/diane/devsite-1558-columns-width
Tickets: 
https://jira.corp.adobe.com/browse/DEVSITE-1557
https://jira.corp.adobe.com/browse/DEVSITE-1558
> Change width behavior of columns and announcement word break behavior 

- hlx_statics/blocks/info-card/info-card.css
Before: https://stage--adp-devsite--adobedocs.aem.page/test/diane/devsite-1658-59-info-card
After: https://diane-ticket-1658-59--adp-devsite--adobedocs.aem.page/test/diane/devsite-1658-59-info-card
Changed height to 160px to accommodate 2 lined header and 3 lined text
ticket: https://jira.corp.adobe.com/browse/DEVSITE-1659
> Change info card height to 160px

- hlx_statics/scripts/lib-helix.js
Wrap a try catch around parsing the redirects json in case it is malformed. This should fix the navs breaking since it relies on the redirects json.
> Fix redirect parsing

- hlx_statics/blocks/hero/hero.css
Before: https://stage--adp-devsite--adobedocs.aem.page/test/diane/devsite-1661-hero-width
After: https://diane-ticket-1661-hero-width--adp-devsite--adobedocs.aem.page/test/diane/devsite-1661-hero-width
Ticket: https://jira.corp.adobe.com/browse/DEVSITE-1661
> Fix for Hero doesn't take entire width in mobile screen

- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/scripts/scripts.js
Apply DevDocs layout logic to DevDocs landing page
https://jira.corp.adobe.com/browse/DEVSITE-1664
https://adobeio.slack.com/archives/C06M1C7UBV3/p1745442031683219
https://stage--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/
https://devsite-1664-landing-page-layout--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/
- https://stage--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/
- https://stage--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
- https://stage--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/support/
- https://stage--adp-devsite-stage--adobedocs.aem.page/developer-distribution/experience-cloud/docs/guides/
- …
> fix: apply DevDocs layout to landing pages

- hlx_statics/blocks/footer/footer.css
Currently in mobile the footre has no padding:
https://developer-dev.adobe.com/developer-console/
With Fix:
https://devsite-1662-footer-in-mobile--adp-devsite--adobedocs.aem.page/developer-console
/
> fix footer padding

- hlx_statics/blocks/info-card/info-card.css
Part of the info card's border is overlapped by the image
- [box-sizing: border-box](https://github.com/AdobeDocs/adp-devsite/blob/stage/hlx_statics/styles/styles.css#L18) was added recently to address overflow issues. This means that padding and border are now included in the width and height.
- Both the [image width](https://github.com/AdobeDocs/adp-devsite/blob/stage/hlx_statics/blocks/info-card/info-card.css#L80-L82) and [box width](https://github.com/AdobeDocs/adp-devsite/blob/stage/hlx_statics/blocks/info-card/info-card.css#L22-L23) were 400px, and so the image overlapped with the box border.
Set the [box-width to 402px](https://github.com/AdobeDocs/adp-devsite/blob/devsite-1667-info-card-border/hlx_statics/blocks/info-card/info-card.css#L23). (401px, so that it fully contains the …
> fix: info card border

- hlx_statics/blocks/onthispage/onthispage.js
**Issue**
When document has two headings with the same text:
- scrolling down to `heading2` jumps back to `link1` in `onthispage` 
- `link1` and `link2` in `onthispage` both point to `heading1`
**Fix** 
Use `heading.id` instead of `heading.text` as `href`
- https://devsite-1627-anchor-link-ids--adp-devsite-stage--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/getting-started#overview
- This has two "Overview" links in `onthispage`
> fix: anchor link ids

- hlx_statics/blocks/codeblock/codeblock.css
- hlx_statics/blocks/codeblock/codeblock.js
Customize `select` element in `codeblock` so it looks more like in Gatsby
Previously we were using "classic" `select` which contain internals that are styled at the operating system level, and can't be targeted using CSS.
This PR uses "customizable" `select` as described in https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Customizable_select, which can be targeted using CSS. This is fairly new and may not be supported by all browsers, but will fallback gracefully to "classic" mode.
https://jira.corp.adobe.com/browse/DEVSITE-1518
https://stage--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/code-block-with-picklist
https://devsite-1518-codeblock-select--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/code-block-with-picklist …
> feat: codeblock customized select

- hlx_statics/blocks/side-nav/side-nav.js
before: 
https://developer-dev.adobe.com/app-builder/docs/intro_and_overview/ 
click on the use cases link in the content.  The side nav doesn't open up and select to the business-case.md page. 
After:
https://devsite-1686-anchorlink--adp-devsite--adobedocs.aem.page/app-builder/docs/intro_and_overview/
click on use cases link again.  The side nav will select to the business case.
> update remove anchorlink from href

- hlx_statics/blocks/codeblock/codeblock.css
Put focus outline back for keyboard accessibility.
We removed the focus outline previously (in https://github.com/AdobeDocs/adp-devsite/pull/83) thinking it was a bug, but it turns out it's a feature.
https://jira.corp.adobe.com/browse/DEVSITE-1518
1. Go to https://devsite-1518-codeblock-a11y--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/code-block-with-picklist
2. Press `Tab` (to go forward) or `Shift + Tab` (to go backward) repeatedly until you get to `select`, and then press `up` or `down` to choose options from the dropdown list.
Notice how there's an outline for the tabs and tab panel, but not for select.
Notice how there's an outline for tabs, select, and tab panel.
> fix: codeblock select keyboard accessibility

- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
Revert badge changes as we do not want any customized css components. 
https://devsite-1693-badge--adp-devsite--adobedocs.aem.page/github-actions-test/test/test-badge
> reverting badge changes

- hlx_statics/blocks/header/header.js
**Issue:** Resize to mobile > resize back to desktop > notice header is messed up
**Root-cause:** Appending `topNavHtml` on resize loses the buttons and icons etc.
- https://github.com/AdobeDocs/adp-devsite/blob/042aa9ed2439735d7c9ff842b918722c64f8debb/hlx_statics/blocks/header/header.js#L439-L443
**Fix:** Remove unnecessary code in `header.js` because `header.css` is already handling responsiveness
- https://github.com/AdobeDocs/adp-devsite/blob/042aa9ed2439735d7c9ff842b918722c64f8debb/hlx_statics/blocks/header/header.js#L368
- https://github.com/AdobeDocs/adp-devsite/blob/042aa9ed2439735d7c9ff842b918722c64f8debb/hlx_statics/blocks/header/header.js#L413
- https://github.com/AdobeDocs/adp-devsite/blob/042aa9ed2439735d7c9ff842b918722c64f8debb/hlx_statics/blocks/header/header.js#L417-L444 …
> fix: header responsiveness

- hlx_statics/blocks/side-nav/side-nav.js
Clean up unused sidenav logic
- remove `if (isSourceGithub()) {` condition and else statement because sidenav is only DevDocs
- remove unneeded event listener to hide sidenav in mobile view because it's being already hidden without it
- [isSourceGithub()](https://github.com/aemsites/devsite-runtime-connector/blob/ec0fbe99c7f387151a72b04571ec9c87e3d52139/src/steps/stringify.ts#L31) is a way to check for DevDocs (which goes through the connector), else is for DevBiz (which doesn't go through the connector) 
- Sidenav is [only DevDocs](https://adobeio.slack.com/archives/C06M1C7UBV3/p1749154072767309)
https://jira.corp.adobe.com/browse/DEVSITE-1723
1. Go to a page with a sidenav such as https://remove-devbiz-sidenav--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
2. Size …
> refactor: clean up because sidenav is only devdocs

- hlx_statics/blocks/side-nav/side-nav.css
- hlx_statics/blocks/side-nav/side-nav.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
- replace resize handlers in `sidenav.js` with media queries in `styles.css`
- move `grid-template-columns` for `main` out of `sidenav.js` and `sidenav.css` and into `styles.css`
- combine checks for `if (IS_DEV_DOCS)` and include `buildSideNav()` because sidenav is only DevDocs (follow-up to  https://github.com/AdobeDocs/adp-devsite/pull/208)
https://jira.corp.adobe.com/browse/DEVSITE-1723
1. Go to a DevDocs page with a sidenav such as https://devsite-1723-grid-cols--adp-devsite-stage--adobedocs.aem.page/express/add-ons/docs/samples
2. Resize window to mobile
3. Confirm sidenav is hidden
4. Resize window to desktop
5. Confirm sidenav is shown
6. Go to a DevBiz page such as https://devsite-1723-grid-cols--adp-devsite-stage--adobedocs.aem.page/commerce/index-onerepo
7. Open up chrome dev …
> refactor: grid-template-columns

- hlx_statics/blocks/side-nav/side-nav.css
- hlx_statics/scripts/lib-adobeio.js
Show sidenav if page exists in `config.md`'s `subPages`
https://jira.corp.adobe.com/browse/DEVSITE-1723
- without sidenav: https://devsite-1723-show-sidenav--adp-devsite--adobedocs.aem.live/github-actions-test/test/no-sidenav-2
- with sidenav: https://devsite-1723-show-sidenav--adp-devsite--adobedocs.aem.live/github-actions-test/test/code
- config.md: https://devsite-1723-show-sidenav--adp-devsite--adobedocs.aem.live/github-actions-test/config.md
> fix: show sidenav if path exists in config subpages

- hlx_statics/scripts/scripts.js
The connector is now returning title if it exists. This update will make sure the document.title is reflected.   
https://devsite-1733-update-title-name--adp-devsite--adobedocs.aem.page/developer-distribution/creative-cloud/docs/guides/branding-guidelines
> update load title

- hlx_statics/blocks/discoverblock/discoverblock.css
Fix `discoverblock` overflow
https://jira.corp.adobe.com/browse/DEVSITE-1751
https://stage--adp-devsite-stage--adobedocs.aem.page/app-builder/docs/resources/blog-articles
https://devsite-1751--adp-devsite-stage--adobedocs.aem.page/app-builder/docs/resources/blog-articles
> fix: discoverblock overflow

- hlx_statics/blocks/onthispage/onthispage.css
Fix `onthispage` right margin
https://jira.corp.adobe.com/browse/DEVSITE-1800
https://stage--adp-devsite-stage--adobedocs.aem.page/app-builder/docs/resources/blog-articles
https://devsite-1800--adp-devsite-stage--adobedocs.aem.page/app-builder/docs/resources/blog-articles
> fix: onthispage right margin

- hlx_statics/blocks/herosimple/herosimple.css
Fix the HeroSimple block gap issue in the devdocs
Previous : https://stage--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/hero/current/herosimple-halfwidth
Update : https://fix-hero-gap-issue--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/hero/current/herosimple-halfwidth
> fix : herosimple gap issue

- hlx_statics/scripts/lib-helix.js
- hlx_statics/scripts/scripts.js
This fixes images when working in local dev mode. The issue is that when in local dev, the html images are just plain img's in a simple div structure eg `<div> <img /> </div>`. However, when a site is deployed in eds, the html structure of images have a `<picture> <source / ><img /></picture`.
> fix: localdev and images

- hlx_statics/blocks/site-wide-banner/site-wide-banner.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/styles/styles.css
previously in safari: 
https://developer-stage.adobe.com/developer-distribution/adobe-connect/ 
After the fix in safari:
Fix is mainly to take out any style: grid-area being called in the code as it's reading differently in safari. 
Grid-area in safari is called grid-row-start, grid-row-end..
> fix issue with safari

- hlx_statics/blocks/cards/cards.css
- hlx_statics/blocks/cards/cards.js
In replace of the text block in the devdocs, we are using cards instead and also need to add the background color support to the cards component. 
Previous: 
https://main--adp-devsite--adobedocs.aem.page/test/louisa/commerce
Fix:
https://devsite-1875-cards-color--adp-devsite--adobedocs.aem.page/test/louisa/commerce
> adding dark gray to cards block

- hlx_statics/blocks/footer/footer.css
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/styles/styles.css
Set RedoclyAPIBlock to full width when frontmatter has `layout: none` in EDS, similar to [Gatsby](https://github.com/adobe/aio-theme?tab=readme-ov-file#full-width-page)
https://jira.corp.adobe.com/browse/DEVSITE-1725
- with `layout: none`
- page: https://devsite-17250-redocly-full-width--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/redocly-api-block-no-layout
- markdown: https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/redocly-api-block-no-layout.md?plain=1#L2
- without `layout: none`
- page: https://devsite-17250-redocly-full-width--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/redocly-api-block-default
- markdown: https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/redocly-api-block- …
> feat: full width RedoclyAPIBlock

- hlx_statics/blocks/accordionitem/accordionitem.css
- hlx_statics/blocks/accordionitem/accordionitem.js
This adds a accordionitem component for devdocs pages.  
https://devsite-1901-devdocs-accordion--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/test-accordion
The way to create the accordion will be like this 
<AccordionItem slots="heading, table, text, code"/>
| Number | Action | Elapsed Real-Time (from beginning) | Playhead Position | Client Request |
| --- | --- | --- | --- | --- |
| 1 | The auto-play function occurs, or play button is pressed, and the video starts loading | 0 | 0 | `/sessionStart?configId=<datastreamID>` |
This call signals the intention of the user to play a video. The player state is not yet `playing`, but is instead `starting`. This call returns a Session ID which is referenced in the following examples with `{SID}`. The `{SID}`, is returned to the …
> adding accordionitem component

- hlx_statics/blocks/breadcrumbs/breadcrumbs.js
- hlx_statics/blocks/superhero/superhero.css
- hlx_statics/blocks/superhero/superhero.js
- hlx_statics/scripts/lib-adobeio.js
- hlx_statics/scripts/lib-helix.js
- hlx_statics/scripts/scripts.js
- hlx_statics/styles/styles.css
Add `centered` and `centeredxl` variants to DevDocs `Superhero` 
https://jira.corp.adobe.com/browse/DEVSITE-1756
DevDocs uses [Gatsby-compatible markdown](https://github.com/adobe/aio-theme?tab=readme-ov-file#hero-block) (source) and DevBiz styling (page):
| | DevDocs Superhero (centered) | DevBiz Superhero (centered) |
| --- | --- | --- |
| Source | https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/superhero/new/superhero-centered.md?plain=1 | https://docs.google.com/document/d/1r70ZJKXHzhzVrG-sPwUrwxb-0vFDdgjzyMCLs9_2IqE/edit?tab=t.0#heading=h.kfcfoa8idwsy |
| Page | https://devdocs-superhero-centered--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/superhero/new/superhero-centered | …
> feat: devdocs superhero centered and centeredxl

- hlx_statics/blocks/superhero/superhero.js
Add DevDocs `half-width` to `Superhero`
https://jira.corp.adobe.com/browse/DEVSITE-1756
DevDocs uses [Gatsby-compatible markdown](https://github.com/adobe/aio-theme?tab=readme-ov-file#hero-block) and DevBiz styling.
- Original half-width (originally from Gatsby):
| | DevDocs | DevBiz |
| --- | --- | --- |
| Source | https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/superhero/new/hero-default.md?plain=1 | https://docs.google.com/document/d/1B4Rjhkhlk3Hc7ce6mRtT1KYr0qCmby8ut3S_bxG2Aoo/edit?tab=t.0 |
| Page | https://devdocs-superhero-halfwidth--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/superhero/new/hero-default | https://devdocs-superhero-halfwidth--adp-devsite--adobedocs.aem.page/test/melissa/superhero/new/hero-default?nocache=175769 …
> feat: devdocs superhero halfwidth

- hlx_statics/blocks/superhero/superhero.css
- hlx_statics/blocks/superhero/superhero.js
Replace SuperHero `half-width` variant from Gatsby-style to Express-style.
Currently, we have two types of `half-width` variants for Hero:
1. Gatsby-style: non-padded, carried over from [aio-theme](https://github.com/adobe/aio-theme?tab=readme-ov-file#hero-block)
2. Express-style: padded, designed by Express team
Pat noted the styles are similar enough to go with the Express team's style for SuperHero. We're discontinuing the Gatsby-style variant since the Express team has been very specific about their design requirements, and Pat believes most teams won't mind this small change.
These pages rendered Gatsby-style on `stage`, but now render Express-style on `remove-gatsby-style-half-width`:
- DevBiz half-width:  https://remove-gatsby-style-half-width--adp-devsite--adobedocs.aem.page/test/m …
> feat: remove gatsby-style half-width variant from superhero

- hlx_statics/blocks/superhero/superhero.css
- hlx_statics/blocks/superhero/superhero.js
- hlx_statics/styles/styles.css
Add `default` variant to `Superhero` block
https://jira.corp.adobe.com/browse/DEVSITE-1756
Both DevBiz and DevDocs `Superhero` `default` use the same style as `HeroSimple` `default`:
- (existing) DevDocs HeroSimple default: https://superhero-default--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/superhero/old/herosimple-default
- (new) DevDocs Superhero default: https://superhero-default--adp-devsite-stage--adobedocs.aem.page/github-actions-test/test/superhero/new/herosimple-default
- (new) DevBiz Superhero default: https://superhero-default--adp-devsite--adobedocs.aem.page/test/melissa/superhero/new/superhero-default?nocache=1757630127977
- DevDocs with 2 buttons, cyan background, and black text:
- <img width="1728" height="870" alt="Screenshot 2025-10-02 at 11 11 36 AM" …
> feat: superhero default
